version: '3'

services:
  site:
    build:
      context: ../
      dockerfile: ./docker/local.site.Dockerfile
    volumes:
      - ../app/client/:/app
    restart: unless-stopped
    networks:
      - mathan_loans

  api:
    build:
      context: ../
      dockerfile: ./docker/local.api.Dockerfile
    volumes:
      - ../app/server/:/home/nodejs/app
    restart: unless-stopped
    networks:
      - mathan_loans

  db:
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - mathan_loans_db_data:/data/postgres
    networks:
      - mathan_loans
    logging:
      driver: "none"
  redis:
    image: bitnami/redis:6.2
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - mathan_loans
    logging:
      driver: "none"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    logging:
      driver: "none"
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - mathan_loans

  nginx:
    restart: unless-stopped
    image: nginx:1.21.6
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:3000"
    networks:
      - mathan_loans
    logging:
      driver: "none"


volumes:
  mathan_loans_db_data:
  pgadmin:


networks:
  mathan_loans:
    external: false
